Exercicio 12 

In [2]:
import sys
from pathlib import Path

# add /src to python path
project_root = Path().resolve().parent
src_path = project_root / "src"
sys.path.append(str(src_path))

print("Added to path:", src_path)

Added to path: C:\Users\elidi\si\src


In [3]:
import numpy as np
from si.neural_networks.layers import DenseLayer, Dropout
from si.neural_networks.optimizers import SGD


In [4]:
np.random.seed(42)

X = np.random.rand(5, 3)   # 5 amostras, 3 features
y = np.random.rand(5, 2)   # target fictício


In [5]:
optimizer = SGD(learning_rate=0.01)


In [6]:
dense = DenseLayer(n_units=4, input_shape=(3,))
dense.initialize(optimizer)

dropout = Dropout(probability=0.5)


In [7]:
print("=== FORWARD (training=True) ===")
out_dense = dense.forward_propagation(X, training=True)
out_dropout = dropout.forward_propagation(out_dense, training=True)

print("Output Dense:\n", out_dense)
print("Output Dropout:\n", out_dropout)


=== FORWARD (training=True) ===
Output Dense:
 [[ 0.00419525  0.33060004 -0.08216107 -0.52192025]
 [ 0.1699845  -0.09037779  0.00522549 -0.04301447]
 [-0.10645795  0.35560716 -0.09917508 -0.48882376]
 [ 0.62796769  0.24118209  0.30241455 -0.133024  ]
 [ 0.22270491 -0.14250484 -0.00203692 -0.05095283]]
Output Dropout:
 [[ 0.          0.66120008 -0.         -0.        ]
 [ 0.         -0.          0.01045097 -0.        ]
 [-0.2129159   0.         -0.19835016 -0.97764752]
 [ 0.          0.48236419  0.6048291  -0.266048  ]
 [ 0.44540982 -0.28500969 -0.00407385 -0.        ]]


In [8]:
print("\n=== BACKWARD ===")
fake_error = np.random.rand(*out_dropout.shape)

error_dropout = dropout.backward_propagation(fake_error)
error_dense = dense.backward_propagation(error_dropout)

print("Error after Dropout:\n", error_dropout)
print("Error after Dense:\n", error_dense)



=== BACKWARD ===
Error after Dropout:
 [[0.         0.04522729 0.         0.        ]
 [0.         0.         0.35675333 0.        ]
 [0.54269608 0.         0.80219698 0.07455064]
 [0.         0.77224477 0.19871568 0.00552212]
 [0.81546143 0.70685734 0.72900717 0.        ]]
Error after Dense:
 [[-0.01358294  0.00486396  0.02105927]
 [ 0.00507818 -0.11754161  0.11002178]
 [ 0.17307227 -0.54286982  0.47643768]
 [-0.22858642  0.01517709  0.41978635]
 [ 0.03063921 -0.5340236   0.92000814]]


In [9]:
print("\n=== FORWARD (training=False) ===")
out_dense_test = dense.forward_propagation(X, training=False)
out_dropout_test = dropout.forward_propagation(out_dense_test, training=False)

print("Output Dense:\n", out_dense_test)
print("Output Dropout (no dropout):\n", out_dropout_test)



=== FORWARD (training=False) ===
Output Dense:
 [[-0.02163535  0.30238874 -0.12176609 -0.52373407]
 [ 0.15040664 -0.11426521 -0.0244394  -0.04404372]
 [-0.12887583  0.33241046 -0.13369261 -0.49049116]
 [ 0.60462178  0.20890526  0.26585337 -0.13438299]
 [ 0.20098154 -0.16943876 -0.03479285 -0.05205073]]
Output Dropout (no dropout):
 [[-0.02163535  0.30238874 -0.12176609 -0.52373407]
 [ 0.15040664 -0.11426521 -0.0244394  -0.04404372]
 [-0.12887583  0.33241046 -0.13369261 -0.49049116]
 [ 0.60462178  0.20890526  0.26585337 -0.13438299]
 [ 0.20098154 -0.16943876 -0.03479285 -0.05205073]]
